### ISSUE TITLE
Health check seems to be wrong on I2P app. Also it is 2 versions behind

### ISSUE THREAD

**Issue by wolf4914** [truenas/apps#2032]
The app is up and running OK, the console works too but shows as deploying.

![Image](https://github.com/user-attachments/assets/b6daa692-3681-4db5-8f7b-302942873e6f)
![Image](https://github.com/user-attachments/assets/97ba6e01-d3fb-4c2d-9492-c0f303070460)
![Image](https://github.com/user-attachments/assets/549be793-4769-43fc-9141-5b5e7ba6bae4)

**Comment by stavros-k** [comment]
Can you shell in the container and run 
```sh
ip=$(getent hosts i2p | awk '{print $1}')
echo $ip

wget http://$ip7657
echo $1

wget http://localhost:7657
echo $1
```

And share the output please?

Thanks

**Comment by wolf4914** [comment]
![Image](https://github.com/user-attachments/assets/dbbdd4e0-6b84-448a-8794-87c0fb8b3749)
It won't let me connect

**Comment by wolf4914** [comment]
I wonder what is it anyway ?

**Comment by stavros-k** [comment]
I've fixed the versioning in https://github.com/truenas/apps/pull/2031
after its merged it should automatically pick up new versions

**Comment by wolf4914** [comment]
Cool - thanks - when is it going to happen?

**Comment by wolf4914** [comment]
> I've fixed the versioning in [#2031](https://github.com/truenas/apps/pull/2031) after its merged it should automatically pick up new versions

It still shows as update available but it won't pick the new one up

**Comment by stavros-k** [comment]
Latest image published is 2.8.1
https://hub.docker.com/r/geti2p/i2p/tags

It won't pick up anything that is not published.
